In [23]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

# 한글 폰트 설정
import platform

if platform.system() == "Windows":
    plt.rcParams["font.family"] = "Malgun Gothic"
elif platform.system() == "Darwin":
    plt.rcParams["font.family"] = "AppleGothic"
else:
    plt.rcParams["font.family"] = "NanumGothic"

plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["figure.figsize"] = (12, 6)

# pandas 출력 옵션
pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 120)
pd.set_option("display.width", 180)

In [24]:
# ============================================================
# 프로젝트 경로 설정
# 다른 환경에서 실행할 경우 ROOT만 본인 프로젝트 경로에 맞게 수정
# ============================================================

ROOT = Path(r"C:\Users\박정수\OneDrive\바탕 화면\공모전\Anti-Churn-Committee")

DATA_RAW_DIR = ROOT / "data" / "raw"
DATA_PROCESSED_DIR = ROOT / "data" / "processed"
DATA_TABLEAU_DIR = ROOT / 'data' / 'tableau'

USER_PROFILE_FILE = "01_user_profile_preprocessed_v2.csv"
EVENT_LOG_FILE = "02_event_log_preprocessed.csv"

USER_PROFILE_PATH = DATA_PROCESSED_DIR / USER_PROFILE_FILE
EVENT_LOG_PATH = DATA_PROCESSED_DIR / EVENT_LOG_FILE

print("USER_PROFILE_PATH:", USER_PROFILE_PATH)
print("EVENT_LOG_PATH   :", EVENT_LOG_PATH)

USER_PROFILE_PATH: C:\Users\박정수\OneDrive\바탕 화면\공모전\Anti-Churn-Committee\data\processed\01_user_profile_preprocessed_v2.csv
EVENT_LOG_PATH   : C:\Users\박정수\OneDrive\바탕 화면\공모전\Anti-Churn-Committee\data\processed\02_event_log_preprocessed.csv

In [25]:
df_raw01 = pd.read_csv(USER_PROFILE_PATH)
df_raw02 = pd.read_csv(EVENT_LOG_PATH)

print("df_raw01 shape:", df_raw01.shape)
print("df_raw02 shape:", df_raw02.shape)

display(df_raw01.head())
display(df_raw02.head())

df_raw01 shape: (12500, 23)
df_raw02 shape: (1757262, 11)

,user_id,signup_date,signup_channel,device,notification_agreed,notification_changed_date,signup_day,signup_month,signup_weekday,first_event_time,first_event_elapsed_hours,first_app_launch_time,app_launch_elapsed_hours,onboarding_completed_time,onboarding_elapsed_hours,app_launch_to_onboarding_hours,is_onboarding_completed,event_count_total,avg_events_per_session,is_signup_log_issue_period,is_no_event_user,is_notification_changed,is_first_event_before_signup
0,U0000001,2025-01-25,오가닉,iOS,True,NaN,2025-01-25,2025-01,토,2025-01-25 07:25:45,7.429167,2025-01-25 07:25:45,7.429167,2025-01-25 07:26:15,7.437500,0.008333,True,515,2.07,False,False,False,False
1,U0000002,2025-05-06,오가닉,iOS,False,2025-05-24,2025-05-06,2025-05,화,2025-05-06 16:23:12,16.386667,2025-05-06 16:23:12,16.386667,NaN,NaN,NaN,False,55,2.62,False,False,True,False
2,U0000003,2025-05-14,오가닉,iOS,False,NaN,2025-05-14,2025-05,수,2025-05-14 11:09:58,11.166111,2025-05-14 11:09:58,11.166111,NaN,NaN,NaN,False,3,1.50,False,False,False,False
3,U0000004,2025-02-23,퍼포먼스광고,Android,True,NaN,2025-02-23,2025-02,일,2025-02-23 07:15:35,7.259722,2025-02-23 07:15:35,7.259722,NaN,NaN,NaN,False,89,1.79,False,False,False,False
4,U0000005,2025-02-18,퍼포먼스광고,Android,True,NaN,2025-02-18,2025-02,화,2025-02-18 12:50:01,12.833611,2025-02-18 12:52:37,12.876944,2025-02-18 12:53:07,12.885278,0.008333,True,442,1.85,False,False,False,False

    user_id           event_time event_type  session_id notification_type  event_date event_month event_weekday  event_hour  is_log_issue_period  is_event_type_missing
0  U0000001  2025-01-25 07:25:45        앱실행  2858201769               NaN  2025-01-25     2025-01             토           7                False                  False
1  U0000001  2025-01-25 07:26:15     온보딩_완료  2858201769               NaN  2025-01-25     2025-01             토           7                False                  False
2  U0000001  2025-01-25 07:26:55     챌린지_탐색  2858201769               NaN  2025-01-25     2025-01             토           7                False                  False
3  U0000001  2025-01-25 07:27:55      챌린지참여  2858201769               NaN  2025-01-25     2025-01             토           7                False                  False
4  U0000001  2025-01-25 20:30:00       알림수신         NaN               광고성  2025-01-25     2025-01             토          20                False                  False

In [26]:
# ============================================================
# 원본 데이터 구조 확인
# ============================================================

print("User_Profile 컬럼")
print(df_raw01.columns.tolist())

print("\nEvent_Log 컬럼")
print(df_raw02.columns.tolist())

print("\nUser_Profile 결측치")
display(df_raw01.isna().sum().sort_values(ascending=False).to_frame("missing_count"))

print("\nEvent_Log 결측치")
display(df_raw02.isna().sum().sort_values(ascending=False).to_frame("missing_count"))

print("\n중복 확인")
print("User_Profile 전체 중복 행:", df_raw01.duplicated().sum())
print("Event_Log 전체 중복 행    :", df_raw02.duplicated().sum())

User_Profile 컬럼
['user_id', 'signup_date', 'signup_channel', 'device', 'notification_agreed', 'notification_changed_date', 'signup_day', 'signup_month', 'signup_weekday', 'first_event_time', 'first_event_elapsed_hours', 'first_app_launch_time', 'app_launch_elapsed_hours', 'onboarding_completed_time', 'onboarding_elapsed_hours', 'app_launch_to_onboarding_hours', 'is_onboarding_completed', 'event_count_total', 'avg_events_per_session', 'is_signup_log_issue_period', 'is_no_event_user', 'is_notification_changed', 'is_first_event_before_signup']

Event_Log 컬럼
['user_id', 'event_time', 'event_type', 'session_id', 'notification_type', 'event_date', 'event_month', 'event_weekday', 'event_hour', 'is_log_issue_period', 'is_event_type_missing']

User_Profile 결측치

                                missing_count
notification_changed_date               10524
app_launch_to_onboarding_hours           6784
onboarding_completed_time                6781
onboarding_elapsed_hours                 6781
first_app_launch_time                      53
app_launch_elapsed_hours                   53
first_event_time                           47
first_event_elapsed_hours                  47
notification_agreed                         0
signup_day                                  0
signup_channel                              0
user_id                                     0
signup_date                                 0
device                                      0
signup_month                                0
signup_weekday                              0
is_onboarding_completed                     0
event_count_total                           0
avg_events_per_session                      0
is_signup_log_issue_period                  0
is_no_event_user                            0
is_notification_changed                     0
is_first_event_before_signup                0

Event_Log 결측치

                       missing_count
notification_type            1538380
session_id                    241502
event_type                     26456
event_time                         0
user_id                            0
event_date                         0
event_month                        0
event_weekday                      0
event_hour                         0
is_log_issue_period                0
is_event_type_missing              0

중복 확인
User_Profile 전체 중복 행: 0
Event_Log 전체 중복 행    : 0

In [27]:
user_df = df_raw01.copy()
event_df = df_raw02.copy()

이벤트 타임 결측치 플레그 처리 및 알수 없음으로

In [28]:
event_df["is_event_type_missing"] = (
    event_df["event_type"].isna()
)

event_df["event_type"] = (
    event_df["event_type"]
    .fillna("알수없음")
)

세션 아이디 전처리

In [29]:
# 결측여부 표시
event_df["is_session_id_missing"] = (
    event_df["session_id"].isna()
)

notification_changed_date의 결측치는 변경이없음을 의미하므로 signup_date값을 채워넣음

In [30]:
user_df["notification_changed_date"] = (
    user_df["notification_changed_date"]
    .fillna(user_df["signup_date"])
)

# 파생컬럼 생성

In [31]:
type(event_df["event_time"])

pandas.Series

사용자 정보랑 결합

In [32]:
event_tableau_df = event_df.merge(
    user_df[
        [
            "user_id",
            "signup_date",
            "signup_month",
            "signup_channel",
            "device",
            "notification_agreed"
        ]
    ],
    on="user_id",
    how="left",
    validate="many_to_one"
)

가입후 경과일

In [33]:
event_tableau_df["event_date"] = pd.to_datetime(
    event_tableau_df["event_date"],
    errors="coerce"
)

event_tableau_df["signup_date"] = pd.to_datetime(
    event_tableau_df["signup_date"],
    errors="coerce"
)

event_tableau_df["days_since_signup"] = (
    event_tableau_df["event_date"]
    - event_tableau_df["signup_date"]
).dt.days

In [34]:
event_tableau_df["days_since_signup"] = (
    event_tableau_df["event_date"]
    - event_tableau_df["signup_date"]
).dt.days

활동 이벤트 분류

In [35]:
#활동 이벤트를 구분
activity_events = [
    "앱실행",
    "온보딩_완료",
    "챌린지_탐색",
    "챌린지참여",
    "수면기록",
    "운동기록",
    "마음챙김",
    "식단기록",
    "알림오픈"
]

In [36]:
event_tableau_df["is_user_activity"] = (
    event_tableau_df["event_type"]
    .isin(activity_events)
)

In [37]:
#알수없음 제외
event_tableau_df["is_unknown_event"] = (
    event_tableau_df["event_type"] == "알수없음"
)

In [38]:
# 세션 기준 분석용 플래그
event_tableau_df["is_valid_session_event"] = (
    event_tableau_df["session_id"].notna()
)

In [39]:
event_tableau_df.head()

,user_id,event_time,event_type,session_id,notification_type,event_date,event_month,event_weekday,event_hour,is_log_issue_period,is_event_type_missing,is_session_id_missing,signup_date,signup_month,signup_channel,device,notification_agreed,days_since_signup,is_user_activity,is_unknown_event,is_valid_session_event
0,U0000001,2025-01-25 07:25:45,앱실행,2858201769,NaN,2025-01-25,2025-01,토,7,False,False,False,2025-01-25,2025-01,오가닉,iOS,True,0,True,False,True
1,U0000001,2025-01-25 07:26:15,온보딩_완료,2858201769,NaN,2025-01-25,2025-01,토,7,False,False,False,2025-01-25,2025-01,오가닉,iOS,True,0,True,False,True
2,U0000001,2025-01-25 07:26:55,챌린지_탐색,2858201769,NaN,2025-01-25,2025-01,토,7,False,False,False,2025-01-25,2025-01,오가닉,iOS,True,0,True,False,True
3,U0000001,2025-01-25 07:27:55,챌린지참여,2858201769,NaN,2025-01-25,2025-01,토,7,False,False,False,2025-01-25,2025-01,오가닉,iOS,True,0,True,False,True
4,U0000001,2025-01-25 20:30:00,알림수신,NaN,광고성,2025-01-25,2025-01,토,20,False,False,True,2025-01-25,2025-01,오가닉,iOS,True,0,False,False,False

D3,D7,D30 리텐션 생성

In [40]:
retention_activity_df = event_tableau_df[
    (event_tableau_df["is_valid_session_event"])
    & (event_tableau_df["is_user_activity"])
    & (event_tableau_df["days_since_signup"]>=0)
].copy()

# 사용자별 리텐션

In [41]:
retention_days = [3, 7, 30]

user_retention_df = user_df[
    [
        "user_id",
        "signup_date",
        "signup_month",
        "signup_channel",
        "device",
        "notification_agreed"
    ]
].copy()

In [42]:
user_retention_df["signup_date"] = pd.to_datetime(
    user_retention_df["signup_date"],
    errors="coerce"
)

In [43]:
#데이터 종료일
data_end_date = event_tableau_df["event_date"].max()

user_retention_df["observable_days"] = (
    data_end_date
    - user_retention_df["signup_date"]
).dt.days

In [44]:
# 리텐션 및 관찰 가능 여부
for day in retention_days:

    retained_users = (
        retention_activity_df.loc[
            retention_activity_df["days_since_signup"] == day,
            "user_id"
        ]
        .dropna()
        .unique()
    )

    user_retention_df[f"D{day}_retained"] = (
        user_retention_df["user_id"]
        .isin(retained_users)
    )

    user_retention_df[f"D{day}_observable"] = (
        user_retention_df["observable_days"] >= day
    )

# 저장

In [45]:
TABLEAU_OUTPUT_DIR = DATA_TABLEAU_DIR

TABLEAU_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


TABLEAU_EVENT_FILE = "tableau_event_detail.csv"
TABLEAU_USER_FILE = "tableau_user_retention.csv"

TABLEAU_EVENT_PATH = TABLEAU_OUTPUT_DIR/ TABLEAU_EVENT_FILE

TABLEAU_USER_PATH = TABLEAU_OUTPUT_DIR/ TABLEAU_USER_FILE

In [46]:
event_tableau_df.to_csv(TABLEAU_EVENT_PATH,index=False,encoding="utf-8-sig",date_format="%Y-%m-%d %H:%M:%S")
user_retention_df.to_csv(TABLEAU_USER_PATH,index=False,encoding="utf-8-sig",date_format="%Y-%m-%d")
print("Tableau 이벤트 상세 파일 저장 완료")
print("경로:", TABLEAU_EVENT_PATH)
print("데이터 크기:", event_tableau_df.shape)

print()

print("Tableau 사용자 리텐션 파일 저장 완료")
print("경로:", TABLEAU_USER_PATH)
print("데이터 크기:", user_retention_df.shape)

Tableau 이벤트 상세 파일 저장 완료
경로: C:\Users\박정수\OneDrive\바탕 화면\공모전\Anti-Churn-Committee\data\tableau\tableau_event_detail.csv
데이터 크기: (1757262, 21)

Tableau 사용자 리텐션 파일 저장 완료
경로: C:\Users\박정수\OneDrive\바탕 화면\공모전\Anti-Churn-Committee\data\tableau\tableau_user_retention.csv
데이터 크기: (12500, 13)